# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddffaf6bf8ef5e0668fcbd90375b856aac597a4099786054744faa1dc312e49ffdaf00a8dfb009ad48eee51b7fa26f846d801063d07c0f14d987f945e1f35798

test:
  secret_key_base: b1bd59ed9259dd618593863cce85bbba24da57b6c1829cbf9e1f10bd9092ecf88195dcc12f67bde7b510ac5f3e9394965ac6d73e8a01c5f469a082c5eba047c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
